/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package programa;

import entidades.Triangulo;
import java.awt.Color;

/**
 *
 * @author Facundo
 */
public class TipoTriangulo extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public TipoTriangulo() {
        initComponents();
        jTextFieldPrimerLado.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jLabelPrimerLado = new javax.swing.JLabel();
        jLabelSegundoLado = new javax.swing.JLabel();
        jLabelTercerLado = new javax.swing.JLabel();
        jTextFieldPrimerLado = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabelRespuesta = new javax.swing.JLabel();
        jButton = new javax.swing.JButton();
        jTextFieldTercerLado = new javax.swing.JTextField();
        jTextFieldSegundoLado = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tipo Triángulo");

        jLabelTitulo.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabelTitulo.setText("Tipo Triángulo");

        jLabelPrimerLado.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelPrimerLado.setText("Ingrese primer lado:");

        jLabelSegundoLado.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelSegundoLado.setText("Ingrese segundo lado:");

        jLabelTercerLado.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelTercerLado.setText("Ingrese tercer lado:");

        jTextFieldPrimerLado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldPrimerLadoKeyPressed(evt);
            }
        });

        jLabel1.setText("cm.");

        jLabel5.setText("cm.");

        jLabel6.setText("cm.");

        jLabelRespuesta.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        jButton.setText("Armar triángulo");
        jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActionPerformed(evt);
            }
        });

        jTextFieldTercerLado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldTercerLadoKeyPressed(evt);
            }
        });

        jTextFieldSegundoLado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldSegundoLadoKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelPrimerLado)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldPrimerLado, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelTercerLado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldTercerLado, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelSegundoLado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldSegundoLado, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addContainerGap(174, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelRespuesta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(jLabelTitulo)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPrimerLado)
                    .addComponent(jTextFieldPrimerLado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSegundoLado)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldSegundoLado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTercerLado)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldTercerLado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelRespuesta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Boton armar triangulo
     * @param evt 
     */
    private void jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActionPerformed
        String l1 = jTextFieldPrimerLado.getText();
        String l2 = jTextFieldSegundoLado.getText();
        String l3 = jTextFieldTercerLado.getText();
        //Pregunta si estan vacios los campos
        if(!l1.isEmpty() && !l2.isEmpty() && !l3.isEmpty()) {
            //Pregunta si los campos son numeros enteros
            if(isNumeric(l1) && isNumeric(l2) && isNumeric(l3)){
                int lado1 = Integer.parseInt(l1);
                int lado2 = Integer.parseInt(l2);
                int lado3 = Integer.parseInt(l3);
                //Pregunta si los 3 lados son positivos
                if(lado1 > 0 && lado2 > 0 && lado3 > 0){
                    Triangulo nuevo = new Triangulo(lado1, lado2, lado3);
                    //Determina si el triangulo cumple la condicion de existencia
                    if(nuevo.esTriangulo(lado1, lado2, lado3)){
                        jLabelRespuesta.setText("Es un triángulo " + nuevo.tipoTriangulo(lado1, lado2, lado3));
                        jLabelRespuesta.setForeground(Color.blue);
                    }else{
                        jLabelRespuesta.setText("No se cumple la condición de existencia.");
                        jLabelRespuesta.setForeground(Color.red);
                    }
                }else{
                    jLabelRespuesta.setText("Todos los lados deben ser mayores a 0.");
                    jLabelRespuesta.setForeground(Color.red);
                }
            }else{
                  jLabelRespuesta.setText("Solo se pueden ingresar números enteros.");
                  jLabelRespuesta.setForeground(Color.red);
            }
        }else{
            jLabelRespuesta.setText("Ningún campo puede quedar vacío.");
            jLabelRespuesta.setForeground(Color.red);
        }
            
    }//GEN-LAST:event_jButtonActionPerformed

    /**
     * Evento para borrar la respuesta
     * @param evt 
     */
    private void jTextFieldPrimerLadoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPrimerLadoKeyPressed
        jLabelRespuesta.setText("");
    }//GEN-LAST:event_jTextFieldPrimerLadoKeyPressed
    /**
     * Evento para borrar la respuesta
     * @param evt 
     */
    private void jTextFieldSegundoLadoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSegundoLadoKeyPressed
        jLabelRespuesta.setText("");
    }//GEN-LAST:event_jTextFieldSegundoLadoKeyPressed

    /**
     * Evento para borrar la respuesta
     * @param evt 
     */
    private void jTextFieldTercerLadoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldTercerLadoKeyPressed
        jLabelRespuesta.setText("");
    }//GEN-LAST:event_jTextFieldTercerLadoKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TipoTriangulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new TipoTriangulo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelPrimerLado;
    private javax.swing.JLabel jLabelRespuesta;
    private javax.swing.JLabel jLabelSegundoLado;
    private javax.swing.JLabel jLabelTercerLado;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JTextField jTextFieldPrimerLado;
    private javax.swing.JTextField jTextFieldSegundoLado;
    private javax.swing.JTextField jTextFieldTercerLado;
    // End of variables declaration//GEN-END:variables

    /**
     * Método que determina si un string es un numero entero
     * @param lado
     * @return 
     */
    private static boolean isNumeric(String lado) {
        try {
            Integer.parseInt(lado);
            return true;
        } catch (NumberFormatException e) {
            return false;
        }
    }
}
